apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web-app

commonLabels:
  app: __APP_NAME__

configurations:
  - kustomizeconfig/var_references.yaml

resources:
  - deployment/deployment.yaml
  - deployment/service.yaml
