apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web-app

bases:
- ../../base

configMapGenerator:
- literals:
  - EXTERNAL_IP=
  - NODE_ENV=development
  name: __APP_NAME__-env

vars:
- fieldref:
    fieldPath: data.EXTERNAL_IP
  name: ConfigMap.__APP_NAME__-env.data.EXTERNAL_IP
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: __APP_NAME__-env

generatorOptions:
  disableNameSuffixHash: true
